### ISSUE TITLE
Not grabbing the right token

### ISSUE THREAD

**Issue by FZKiritsugu** [ZeroM3m0ry/Discord-Token-Grabber#1]
it sent me an invalid token, but after searching the .ldb files myself, i couldn't find the right token either. logging in through chrome i confirmed that the token is different

It'd be nice to search for all tokens in the same file (not to return when one is found)

**Comment by ZeroMemoryEx** [comment]
cuz it only search in ldb path for token if no token found or the token is encrypted  ... , its will go and grab it from process memory .
i didnt add any feature that grab the token from browser thats why it give you different token.
and thanks for ur feedback ill add this feature in next update .

**Comment by FZKiritsugu** [comment]
the program works really well, I just had more than one token in the same idb file, so it grabbed the first one that wasn't valid, and because it found a token the program quit. that's why i made the recommendation to search for all tokens inside idb

**Comment by ZeroMemoryEx** [comment]
cool ,thanks for your feedback .
